spring:
  application:
    name: fdums-discovery-eureka-lfy
server:
  port: 8761
eureka:
  client:
    #registerWithEureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: discovery